services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=silverspin'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306'
